version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
      timezone: Etc/UCT
    reviewers:
      - "Johannes-Schneider"
    open-pull-requests-limit: 10